apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: producer
  template:
    metadata:
      labels:
        app: producer
    spec:
      containers:
        - name: producer
          image: your-dockerhub-username/producer:latest
          command: ["node", "src/infrastructure/kafka/producer.js"]
          envFrom:
            - configMapRef:
                name: app-config
